export const products = [
  {
    name: 'Bloco 9cm  (Vazado Com fundo)',
    price: 'R$ 2,99',
    category: 'bloco',
    description: '9x19x39',
    image: '/products/bloco_9x19x39_com_fundo.png',
  },
  {
    name: 'Bloco 12cm',
    price: 'R$ 3,49',
    category: 'bloco',
    description: '12x19x39 Vazado',
    image: '/products/bloco_12x19x39_vazado.png',
  },
  {
    name: 'Bloco 14cm',
    price: 'R$ 3,79',
    category: 'bloco',
    description: '14x19x39 Vazado',
    image: '/products/bloco_14x19x39_vazado.png',
  },
  {
    name: 'Bloco 19cm',
    price: 'R$ 4,99',
    category: 'bloco',
    description: '19x19x39 Vazado',
    image: '/products/bloco_19x19x39_vazado.png',
  },
  {
    name: 'Meio Bloco 9cm',
    price: 'R$ 2,20',
    category: 'bloco',
    description: '9x19',
    image: '/products/meio_bloco_9x19.jpg',
  },
  {
    name: 'Meio Bloco 12cm',
    price: 'R$ 2,40',
    category: 'bloco',
    description: '12x19',
    image: '/products/meio_bloco_12x19.jpg',
  },
  {
    name: 'Meio Bloco 14cm',
    price: 'R$ 2,85',
    category: 'bloco',
    description: '14x19',
    image: '/products/meio_bloco_14x19.jpg',
  },
  {
    name: 'Meio Bloco 19cm',
    price: 'R$ 3,55',
    category: 'bloco',
    description: '19x19',
    image: '/products/meio_bloco_19x19.jpg',
  },
  {
    name: 'Bloco Raquete',
    price: 'R$ 5,99',
    category: 'bloco',
    description: '19x39',
    image: '/products/meio_bloco_19x32.jpg',
  },
  {
    name: 'Bloco Ecológico',
    price: 'R$ 5,99',
    category: 'bloco',
    description: '19x32',
    image: '/products/bloco_ecologico.jpg',
  },
  {
    name: 'Bloco Jardineira',
    price: 'R$ 5,99',
    category: 'bloco',
    description: '12x30x39',
    image: '/products/meio_bloco_jardineira.jpg',
  },
  {
    name: 'Canaleta 9cm',
    price: 'R$ 3,29',
    category: 'canaleta',
    description: '9x19x39',
    image: '/products/canaleta_9x19x39.jpg',
  },
  {
    name: 'Canaleta 12cm',
    price: 'R$ 4,29',
    category: 'canaleta',
    description: '12x19x39',
    image: '/products/canaleta_12x19x39.png',
  },
  {
    name: 'Canaleta 14cm',
    price: 'R$ 4,79',
    category: 'canaleta',
    description: ' 14x19x39',
    image: '/products/canaleta_14x19x39.png',
  },
  {
    name: 'Canaleta 19cm',
    price: 'R$ 6,19',
    category: 'canaleta',
    description: '19x19x39',
    image: '/products/canaleta_19x19x39.png',
  },
  {
    name: 'Canaleta Baldrame 22cm',
    price: 'R$ 5,99',
    category: 'canaleta',
    description: '22x19x34',
    image: '/products/canaleta_baldrame_15x30.png',
  },
  {
    name: 'Canaleta Baldrame 27cm',
    price: 'R$ 6,49',
    category: 'canaleta',
    description: '27x19x34',
    image: '/products/canaleta_baldrame_20x30.png',
  },
  {
    name: 'Muro Pré Moldado',
    category: 'muro',
    price: '',
    description: '1,80cm | 2,20cm | 2,70cm',
    image: '/products/muro_pre_moldado.jpg',
  },
  {
    name: 'Manilhas',
    category: 'manilha',
    price: 'R$ 75,00',
    description: '75x50cm | 80x50cm | 90x50cm | 1mx50cm | 1,10mx50cm',
    image: '/products/manilha.jpg',
  },
  {
    name: 'Tubos Pluviais',
    category: 'manilha',
    price: 'R$ 5,99',
    description: '30X1m | 40X1m | 50X1m | 60X1m ',
    image: '/products/tubo.jpg',
  },
  {
    name: 'Tubos',
    category: 'manilha',
    price: 'R$ 37,00',
    description: '30x50 | 50x50',
    image: '/products/tubos.jpg',
  },
  {
    name: 'Anel Tipo Tubo com Encaixe',
    category: 'manilha',
    price: 'R$ 37,00',
    description: '50x50',
    image: '/products/anel_tubo.jpg',
  },
  {
    name: 'Calhas',
    category: 'manilha',
    price: 'R$ 65,00',
    description: '30x1m | 40x1m | 50x1m | 60x1m',
    image: '/products/calhas.jpg',
  },
  {
    name: 'Grelhas Armadas',
    category: 'calcamento',
    price: 'R$ 56,00',
    description: '50x48x6,5',
    image: '/products/grelhas.jpg',
  },
  {
    name: 'Pezão de Concreto',
    category: 'calcamento',
    price: 'R$ 16,00',
    description: '53x28x5',
    image: '/products/pezao.jpg',
  },
  {
    name: 'Pingadeira de Concreto',
    category: 'decoracao',
    price: 'R$ 18,00',
    description: '17x80cm | 19x80cm',
    image: '/products/pingadeira.jpg',
  },
  {
    name: 'Placa Desenhada',
    category: 'calcamento',
    price: 'R$ 16,00',
    description: '50X50',
    image: '/products/placa_desenhada.jpg',
  },
  {
    name: 'Placa Lisa',
    category: 'calcamento',
    price: 'R$ 23,00',
    description: '50x50x5 Armado',
    image: '/products/placa_lisa.jpg',
  },
  {
    name: 'Placa Aranha',
    category: 'calcamento',
    price: 'R$ 15,00',
    description: '45x45x3',
    image: '/products/placa_aranha.jpg',
  },
  {
    name: 'Caixa de Passagem',
    category: 'manilha',
    price: 'R$ 70,00',
    description: 'Sem Fundo | Com Fundo | Tampa da Caixa | 52x48x42',
    image: '/products/caixa_passagem.jpg',
  },
  {
    name: 'Caixa de Telefone',
    category: 'manilha',
    price: 'R$ 20,00',
    description: '29x29',
    image: '/products/caixa_telefone.jpg',
  },
  {
    name: 'Cobogós',
    category: 'decoracao',
    price: 'R$ 18,00',
    description: 'Grande 39x39 | Pequeno 29x29',
    image: '/products/cobogos.jpg',
  },
  {
    name: 'Coquegrama',
    category: 'calcamento',
    price: 'R$ 16,00',
    description: '33x43x7',
    image: '/products/coquegrama.jpg',
  },
  {
    name: 'Meio Fio',
    category: 'calcamento',
    price: 'R$ 17,00',
    description:
      'Palito 1mtx20cm | Padrão Condomínio 9x24x1mt | Padrão NovaCap 12x29x1mt ',
    image: '/products/meio_fio.jpg',
  },
  {
    name: 'Meio Fio Ondulado',
    category: 'calcamento',
    price: 'R$ 17,00',
    description: '80x20x4',
    image: '/products/meio_fio_ondulado.jpg',
  },
  {
    name: 'Banco com encosto',
    category: 'decoracao',
    price: 'R$ 360,00',
    description: '1,48x0,35',
    image: '/products/banco_com_encosto.jpg',
  },
  {
    name: 'Banco sem encosto',
    category: 'decoracao',
    price: 'R$ 260,00',
    description: '1,60x0,39',
    image: '/products/banco_sem_encosto.jpg',
  },
  {
    name: 'Casa Pré-Moldada',
    category: 'muro',
    price: 'R$ 270,00',
    description: 'Placa lisa 1,45x0,45 | Placa tijolinho 1,00x0,52 ',
    image: '/products/casa.jpg',
  },
  {
    name: 'Placas',
    category: 'muro',
    price: 'R$ 32,00',
    description: '1mtx0,52 | 1,45x0,45 | 1,90x0,45 ',
    image: '/products/placa.jpg',
  },
  {
    name: 'Postes',
    category: 'muro',
    price: 'R$ 25,00',
    description: '',
    image: '/products/postes.jpg',
  },
  {
    name: 'Estacas',
    category: 'muro',
    price: 'R$ 15,00',
    description: '',
    image: '/products/estacas.jpg',
  },
  {
    name: 'Intertravado',
    category: 'calcamento',
    price: 'R$ 65,00',
    description: '20x10x6 | 45 pçs por m²',
    image: '/products/calcamento_intertravado.jpg',
  },
  {
    name: 'Sextavado',
    category: 'calcamento',
    price: 'R$ 62,00',
    description: '29x29x4,5 | 12 pçs por m²',
    image: '/products/calcamento_sextavado.jpg',
  },
  {
    name: 'Tijolinho',
    category: 'calcamento',
    price: 'R$ 82,00',
    description: '20x10x6 | 50 pçs por m²',
    image: '/products/tijolinho.jpg',
  },
  {
    name: 'Suporte Para Energia Solar ',
    category: 'suporte',
    price: 'R$ 100,00',
    description:
      '1,60m de comprimento | 67cm a parte maior | 40cm a parte menor | 40cm a parte menor',
    image: '/products/suporte_energia_solar.jpg',
  },
  {
    name: 'Suporte Para Energia Solar - Caixa Maciça ',
    category: 'suporte',
    price: 'R$ 25,00',
    description: '20x20 com 25 MPA | Peso: 21kg',
    image: '/products/suporte_energia_solar_caixa_macica.jpg',
  },
  {
    name: 'Piso tátil',
    category: 'calcamento',
    price: 'R$ 25,00',
    description: '',
    image: '/products/piso_tatil.jpg',
  },
  {
    name: 'Piso tátil',
    category: 'calcamento',
    price: 'R$ 25,00',
    description: '',
    image: '/products/piso_tatil2.jpg',
  },
  {
    name: 'Revestimentos em Concreto',
    category: 'decoracao',
    price: 'R$ 25,00',
    description: '',
    image: '/products/revestimento.jpg',
  },
];
