export const products = [
  {
    name: 'Bloco 9cm',
    price: 'R$ 2,99',
    category: 'bloco',
    description: '9x19x39 Com fundo',
    image: '/products/bloco_9x19x39_com_fundo.png',
  },
  {
    name: 'Bloco 9cm',
    price: 'R$ 2,89',
    category: 'bloco',
    description: '9x19x39 Vazado',
    image: '/products/bloco_9x19x39_vazado.png',
  },
  {
    name: 'Bloco 12cm',
    price: 'R$ 3,49',
    category: 'bloco',
    description: '12x19x39 Vazado',
    image: '/products/bloco_12x19x39_vazado.png',
  },
  {
    name: 'Bloco 14cm',
    price: 'R$ 3,79',
    category: 'bloco',
    description: '14x19x39 Vazado',
    image: '/products/bloco_14x19x39_vazado.png',
  },
  {
    name: 'Bloco 19cm',
    price: 'R$ 4,99',
    category: 'bloco',
    description: '19x19x39 Vazado',
    image: '/products/bloco_19x19x39_vazado.png',
  },
  {
    name: 'Canaleta 9cm',
    price: 'R$ 3,29',
    category: 'canaleta',
    description: '9x19x39',
    image: '/products/canaleta_9x19x39.jpg',
  },
  {
    name: 'Canaleta 12cm',
    price: 'R$ 4,29',
    category: 'canaleta',
    description: '12x19x39',
    image: '/products/canaleta_12x19x39.png',
  },
  {
    name: 'Canaleta 14cm',
    price: 'R$ 4,79',
    category: 'canaleta',
    description: ' 14x19x39',
    image: '/products/canaleta_14x19x39.png',
  },
  {
    name: 'Canaleta 19cm',
    price: 'R$ 6,19',
    category: 'canaleta',
    description: '19x19x39',
    image: '/products/canaleta_19x19x39.png',
  },
  {
    name: 'Canaleta Baldrame 15cm',
    price: 'R$ 5,99',
    category: 'canaleta',
    description: '15x30',
    image: '/products/canaleta_baldrame_15x30.png',
  },
  {
    name: 'Canaleta Baldrame 20cm',
    price: 'R$ 6,49',
    category: 'canaleta',
    description: ' 20x30',
    image: '/products/canaleta_baldrame_20x30.png',
  },
  {
    name: 'Muro Pré Moldado',
    category: 'muro',
    price: [
      'R$ 144,99/MT na altura de 1,80cm',
      'R$ 169,99/MT na altura de 2,20cm',
      'R$ 229,99/MT na altura de 2,70cm',
    ],
    description: '',
    image: '/products/muro_pre_moldado.jpg',
  },
];
